AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Testing SQS

Resources:
  TestSqsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 60
      Architectures:
        - x86_64
      Policies:
        - CloudWatchFullAccess
        - AmazonSQSFullAccess
      Tracing: Active
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:16
      Environment:
        Variables:
          QUEUE_URL: !GetAtt MySqsQueue.QueueUrl
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 10

  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 200
      QueueName: "q_test_name"